---
title: "Kevin Wong"
output:
  html_document:
    theme: readable
---

<center><h1>Kevin Wong</h1></center>

```{r}
kevin_ho_prop_test(p = .6, p_hat = 158/250, n = 250, test = "two")
```

```{r}
x = c(50, 44, 47, 40, 54)
y = c(10, 13, 9, 5, 7)

x = c(2, 3, 4)
y = c(3, 8, 10)
z = c(2, 5, 2)
cor(z, y)


```

```{r}
kevin_ho_mean_test(mu = 16, x_bar = 17.4, n = 80, sd = 5.7, test = "right", type = "t")
6 / sqrt(31)

sqrt(2500)
((2.575 * 6) / .1)^2
sqrt((.84 * .16 / 800))

sqrt(.86 * .14 / 50)
```


```{r}
kevin_ho_mean_test(
  mu = 90,
  x_bar = 94.1,
  sd = 17,
  n = 80,
  test = "right",
  type = "t"
)


kevin_ho_prop_test(
  p = .12,
  p_hat = 33/200,
  n = 200,
  test = "right"
)

121/700
```




```{r}
kevin_ho_prop_test(p = .12, p_hat = .13375, n = 800, test = "right")
```


```{r}
a = c(0,    0.1, 0.2,  0.3, 0.4,  0.5, 0.6,  0.7, 0.8,  0.9, 1)
b = c(0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75)

l = lm(b ~ a)
coefficients(l)
plot(b, a)
lines(l)

.5 * .9 + 0.25
.9 * .25 + .5
```



```{r}
kevin_ci_mean(mean = 32.6, sd = .83, type = "z", confidence_level = 95, n = 49)
kevin_ci_mean(mean = 32.6, sd = .83, type = "t", confidence_level = 95, n = 49)
kevin_ci_mean(mean = 32.6, sd = .83, type = "t", confidence_level = 99, n = 49)

kevin_ci_prop(mean = 37/98, confidence_level = 90, n = 98)
```

```{r}
8 * 16.865 / 2.733

g = c(114.8, 90.8, 62.1, 149.3, 159.1, 146.5, 83.7, 100.5)
h = 130
7 * g / h

62.1 * 19 / 144



```


```{r}
-(4/5)*3.75^2 + (6*3.75) - (36/5)
```




















```{r}
kevin_ci_prop(p_hat = 562/814, confidence_level = 90, n = 914)
```



```{r}
1.96 * 562/814 
```


```{r}
invT(.995,14)
128/ 64 + 72/ 36

<<<<<<< HEAD

```

```{r}
kevin_ci_mean(mean = 8.9, sd = 13.5, n = 68, type = "t", confidence_level = 99)

1.645 * 1.645 * .30350806 * .30350806 / 0.015 / 0.015

84

-(5.5^2) * 4 / 5 + (44/5 * 5.5)  - 57/5
```



```{r}
304000 / (1.02 ^ 10)

2.575 * 2.575 * . / (0.01)^2

invNorm(.995)
```



```{r}
37 * 5.7 / 4
invChi(.975, 19)
chisqcdf(24.06667, 9999999, 19)
chisqcdf(-121, 11.875, 19)

```
=======

```

```{r}
kevin_ci_mean(mean = 1.01, sd = .30350806, n = 450, type = "t", confidence_level = 99)

1.645 * 1.645 * .30350806 * .30350806 / 0.015 / 0.015

84

-(5.5^2) * 4 / 5 + (44/5 * 5.5)  - 57/5
```
>>>>>>> 4c9eea599987273db5d0ff5144594d5c26c5b83e


```{r}
x_bar_aa  = 39.4
s_aa      = 5
n_aa      = 40

x_bar_bb  = 37.4
s_bb      = 6
n_bb      = 40

kevin_ho_two_sample_mean_test(
  x_bar_A = x_bar_aa,
  s_A = s_aa,
  n_A = n_aa,
  
  x_bar_B = x_bar_bb,
  s_B = s_bb,
  n_B = n_bb,
  
  test = "two"
)

kevin_ci_2_sample_mean(
  x_bar_A = x_bar_aa,
  s_A = s_aa,
  n_A = n_aa,
  
  x_bar_B = x_bar_bb,
  s_B = s_bb,
  n_B = n_bb,
  
  confidence_level = 90,
  average = TRUE
)

90/12 + 8.5

invT(.975, 20)

3 - 2.0859 * 4
```

