---
title: "fin221"
author: "Kevin Wong"
date: "9/11/2018"
output: html_document
---

```{r}
# FINDING FUTURE VALUE
fv = 0
pv = .93
r = .0225
n = 1
t = 1000

fv = pv * (1 + r / n) ^ (n * t); fv
```

```{r}
#FINDING PRESENT VALUE
fv = 10000
pv = 0
r = .07
n = 1
t = 10

pv1 = fv / ((1 + r / n) ^ (n * t)); pv1
```

```{r}
#FINDING INTEREST RATE
fv = 21936.95
pv = 12800
r = r
n = 1
t = 7


r = n * ((fv / pv) ^ (1 / (n * t)) - 1); r
```


```{r}
# MEGA MILLIONS EXAMPLE
winnings = 000000
t = 30
r = .045
avg = winnings / t

amount = avg * (( 1 - (1 / (1 + r) ^ t)) / r) * (1 + r); amount
```

```{r}
# MEGA MILLIONS EXAMPLE
winnings = 227000000
t = 30
r = .040
avg = winnings / t

amount = avg * (( 1 - (1 / (1 + r) ^ t)) / r) * (1 + r); amount
```



```{r}
# ANNUAL ANNUITY WITHDRAWAL
r = 6
n_years = 25
n_compounds_per_year = 1
present_value = 1500000

r = r / 100
a = n_years
b = n_compounds_per_year
pv = present_value

P = pv / (1 + ((1 - (1 / (1 + r) ^ (a - 1)))) / r); P
```

```{r}
# FUTURE VALUE EQUAL DEPOSITS

each_deposit = 100
n_deposits = 53
n_compounds_per_year = 4
n_years = 13
r = 6

a = each_deposit
b = n_years
c = n_compounds_per_year
n = n_deposits
r = r / 100

fv = a * ((1 + (r / c)) ^ (b * c) - 1) / (r / c); fv
```

```{r}
#FINDING PRESENT VALUE
fv = 10000
pv = 0
r = .07
n = 365
t = 10

pv1 = fv / ((1 + r / n) ^ (n * t)); pv1
```

```{r}
# FINDING FUTURE VALUE
fv = 0
pv = 5
r = .0725
n = 365
t = 10

fv = pv * (1 + r / n) ^ (n * t); fv
```

```{r}
#KRISTA NEEDS TO MAKE SOME HOUSE REPAIRS IN THREE YEARS THAT WILL COST 9000. SHE HAS SOME MONEY IN AN ACCOUNT EARNING 7% ANNUAL INTERST. HOW MUCH MONEY NEEDS TO BE IN THE ACCOUNT TODAY SO SHE WILL HAVE ENOUGH TO PAY FOR THE REPAIRS?

total_cost = 9000
years = 3
r = 0.07
answer = total_cost / (1 + r) ^ years; answer
#correct
```


```{r}
# UNFORTUNATELY, VANESSA DOESN'T HAVE ENOUGH MONEY IN HER ACCOUNT RIGHT NOW. SHE NEEDS TO MAKE ADDITIONAL CONTRIBUTIONS AT THE END OF EACH OF THE NEXT THREE YEARS TO BE ABLE TO PAY FOR THE REPAIRS. HER ACCOUNT CURRENTLY HAS $4500, WHICH, ALONG WITH HER ADDITIONAL CONTRIBUTIONS, IS EXPECTED TO CONTINUE EARNING 7% ANNUAL INTEREST. IF SHE MAKES EQUAL CONTRIBUTIONS EACH YEAR, HOW LARGE MUST EACH CONTRIBUTION BE FOR VANESSA TO HAVE $9000 AFTER THREE YEARS?


total_cost = 9000
r = .07
initial_payment = 4500
years = 3
a = initial_payment

(total_cost - a* (1+r)^3) / ((1 + r)^2 + (1 + r)^1 + (1 + r)^0)

# adjust years accordingly
```

```{r}
# YOU JUST WON $50,000 ON A SCRATCH-OFF LOTTERY TICKET. YOU PLAN TO SAVE THE MONEY IN A RETIREMENT ACCOUNT EXPECTED TO RETURN 6% PER YEAR. IF YOU INTEND TO RETIRE IN 45 YEARS, HOW MUCH ARE THESE LOTTERY WINNINGS EXPECTED TO BE WORTH WHEN YOU RETIRE?

won = 50000
r = .06
years = 45

won * (1 + r) ^ years
#CORRECT
```

```{r}
# IF YOU FIND AN ACCOUNT THAT PAYS 7% ANNUAL INTEREST INSTEAD OF 6%, HOW MUCH WOULD HAVE AT RETIREMENT?

won = 50000
r = .07
years = 45

won * (1 + r) ^ years
#CORRECT
```
```{r}
# SUPPOSE THE NEW RETIREMENT ACCOUNT ACTUALLY PAYS 7% INTEREST PER YEAR AND PAYS INTEREST SEMIANNUALLY. HOW MUCH MONEY WOULD HAVE AT RETIREMENT?

won = 50000
r = .07
years = 45
n = 2

won * (1 + r / n) ^ (n * years)
#CORRECT
```

```{r}
#JOHN HAS DECIDED TO RETIRE ONCE HE HAS $1000000 IN HIS RETIREMENT ACCOUNT. AT THE END OF EACH YEAR, HE WILL CONTRIBUTE 7000 TO THE ACCOUNT, WHICH IS EXPECTED TO PROVIDE AN ANNUAL RETURN OF 6.2%. HOW MANY YEARS WILL IT TAKE UNTIL HE CAN RETIRE?

# excel nper(6.2%, -7000,0,1000000)
#CORRECT
```
```{r}
# SUPPOSE JOHN'S FRIEND, TOMMY, HAS THE SAME RETIREMENT PLAN, SAVING $7000 AT THE END OF EACH YEAR AND RETIRING ONCE HE HITS $1000000. HOWEVER, TOMMY'S ACCOUNT IS EXPECTED TO PROVIDE AN ANNUAL RETURN OF 7.9%. HOW MUCH SOONER CAN TOMMY RETIRE?

# excel nper(6.2%, -7000,0,1000000)
#CORRECT
```


```{r}
# AFTER 25 YEARS, NEITHER JOHN NOR TOMMY WILL HAVE ENOUGH MONEY TO RETIRE, BUT HOW MUCH MORE MONEY WILL TOMMY'S ACCOUNT BE WORTH AT THIS TIME?

# FV(7.9%,25,-7000,0) - FV(6.2%,25,-7000,0)
#CORRECT
```

```{r}
#JOHN IS JEALOUS OF TOMMY BECAUSE TOMMY IS SCHEDULE TO RETIRE BEFORE HIM, SO JOHN DECIDES TO MAKE WHATEVER END-OF-YEAR CONTRIBUTION IS NECESSARY TO REACH THE $1000000 GOAL AT THE SAME TIME AS TOMMY. IF JOHN CONTINUES TO EARN 6.2% ANNUAL INTEREST, WHAT ANNUAL CONTRIBUTIONS MUST HE MAKE IN ORDER TO RETIRE AT THE SAME TIME AS TOMMY?


#33 BECAUSE 38-5 = 33
# PMT(6.2%,33,0,1000000)

#CORRECT
```

```{r}
#BRIAN JUST JOINED A NEW GYM AND SIGNED UP FOR A ONE-YEAR MEMBERSHIP. MEMBERSHIP FEES CAN BE PAID IN 12 MONTHLY PAYMENTS OF $60, DUE AT THE BEGINNING OF EACH MONEY OR IN ONE PAYMENT TODAY. IF THE APPROPRIATE INTEREST RATE IS 10%, HOW MUCH SHOULD HE PAY FOR THE ANNUAL MEMBERSHIP?

payment = 60
r = .10
n = 12
payment + payment / (1 + r / n)^1 + payment / (1 + r / n)^2 + payment / (1 + r / n)^3 + payment / (1 + r / n)^4 + payment / (1 + r / n)^5 + payment / (1 + r / n)^6 + payment / (1 + r / n)^7 + payment / (1 + r / n)^8 + payment / (1 + r / n)^9 + payment / (1 + r / n)^10 + payment / (1 + r / n)^11 

```

```{r}
# LIKE MANY COLLEGE STUDENTS, JULIE APPLIED FOR AND GOT A CREDIT CARD THAT HAS AN ANNUAL PERCENTAGE RATE (APR) OF 12%. THE FIRST THING SHE DID WAS BUY A NEW STEREO SYSTEM FOR $300. AT THE END OF THE MONTH, HER CREDIT CARD STATEMENT SAID SHE ONLY NEEDED TO MAKE A MINIMUM PAYMENT OF $10. ASSUME JULIE MAKES HER PAYMENT WHEN SHE SEES HER STATEMENT AT THE END OF EACH MONTH. IF JULIE DOESN'T CHARGE ANYTHING ELSE AND ONLY MAKES THE MINIMUM MONTHLY PAYMENTS, APPROXIMATELY HOW MANY MONTHS WOULD IT TAKE HER TO COMPLETELY PAY OFF THE STEREO SYSTEM. ASSUME THAT THE CREDIT CARD COMPANY COMPOUNDS INTEREST AT THE END OF EACH MONTH.

# nper() =PMT(1%,12,-300,0)
# guess and check
```


```{r}
# A BANK JUST APPROVED YOUR SMALL BUSINESS LOAN FOR $25,000. THE LOAN HAS AN INTEREST RATE OF 12% AND WILL BE REPAID WITH 10 END-OF-YEAR PAYMENTS. WHAT IS THE REQUIRED ANNUAL LOAN PAYMENT?
r = 0.105
loan = 25000
years = 10

p = (r * loan) / ( 1 - (1 + r )^-(years)); p
```

```{r}
#HALFWAY THROUGH THE LOAN'S LIFE, WHAT IS THE LOAN'S REMAINING BALANCE?

a = loan - (p - (loan - (loan - (loan * r)))); a
b = a - (p - (a - (a - (a * r)))); b
c = b - (p - (b - (b - (b * r))))
d = c - (p - (c - (c - (c * r))))
e = d - (p - (d - (d - (d * r))))
e

4156.43 - 2283.29


4156.43 * 5

(2625 + 2464 + 2286 + 2090 + 1873) / (4156.43 * 5)
```

```{r}
# YOU'VE DECIDED TO BUY A HOUSE THAT IS VALUED AT $1000000. YOU HAVE $100000 TO USE AS A DOWN PAYMENT ON THE HOUSE AND WANT TO TAKE OUT A MORTGAGE FOR THE REMAINDER OF THE PURCHASE PRICE. YOUR BANK HAS APPROVED YOUR $900000 MORTGAGE AND IS OFFERING A STANDARD 30-YEAR MORTGAGE AT A 12% FIXED NOMINAL INTEREST RATE (CALLED THE LOAN'S ANNUAL PERCENTAGE RATE, OR APR). UNDER THIS LOAN PROPOSAL, YOUR MORTGAGE WILL BE ___ PER MONTH. (NOTE: ROUND THE FINAL VALUE OF ANY INTEREST RATE USED TO FOUR DECIMAL PLACES)

principal = 900000
n_years_30 = 30
n_months_30 = n_years_30 * 12
apr = .12
interest_rate = apr / 12
# pmt_30 = PMT(12/1200,360,-850000)
pmt_30 = 9251.71
total_payments_30 = pmt_30 * n_months_30


interest30 = total_payments - principal; interest30
#CORRECT
```

```{r}
#YOUR FRIENDS SUGGEST THAT YOU TAKE A 15-YEAR MORTGAGE, BECAUSE A 30-YEAR MORTGAGE IS TOO LONG AND YOU WILL PAY A LOT OF MONEY ON INTEREST. IF YOUR BANK APPROVES A 15-YEAR, $900,000 LOAN AT A FIXED NOMIAL INTEREST RATE OF 12% (APR), THEN THE DIFFERENCE IN THE MONTHLY PAYMENT OF THE 15-YEAR MORTGAGE AND 30-YEAR MORTGAGE WILL BE ___? (NOTE: ROUND THE FINAL VALUE OF ANY INTEREST RATE USED TO FOUR DECIMAL PLACES.)

pmt_15 = 10801.51
pmt_15 - pmt_30
#CORRECT
```

```{r}
# IT IS LIKELY THAT YOU WON'T LIKE THE PROSPECT OF PAYING MORE MONEY EACH MONTH, BUT IF YOU DO TAKE A 15-YEAR MORTGAGE, YOU WILL MAKE FAR MORE FEWER PAYMENTS AND WILL PAY A LOT LESS INTEREST. HOW MUCH MORE TOTAL INTEREST WILL YOU PAY OVER THE LIFE OF THE LOAN IF YOU TAKE OUT A 30-YEAR MORTGAGE INSTEAD OF A 15-YEAR MORTGAGE?

principal = 900000
n_years_15 = 15
n_months_15 = n_years_15 * 12
apr = .12
interest_rate = apr / 12
# pmt_15 = PMT(12/1200,180,-850000)
pmt_15 = 10801.51
total_payments_15 = pmt_15 * n_months_15


interest15 = total_payments_15 - principal; interest15

interest30 - interest15
#CORRECT
```

```{r}
n = 4 #quarterly
nominal = .044
periodic_rate = nominal / n
p = periodic_rate

a = (1 + (nominal / n))^n - 1
effective_interest_rate = a
effective_interest_rate #CORRECT
```

```{r}
n = 2 #semiannually
nominal = .04
periodic_rate = nominal / n
p = periodic_rate

a = (1 + (nominal / n))^n - 1
effective_interest_rate = a
effective_interest_rate
#CORRECT
```

```{r}
#SUPPOSE YOU WANT TO DEPOSIT $20000 IN A SAVINGS ACCOUNT THAT PAYS A NOMINAL RATE OF 11%, BUT INTEREST IS COMPOUNDED DAILY. BASED ON A 365-DAY YEAR, HOW MUCH WOULD YOU HAVE IN THE ACCOUNT AFTER NINE MONTHS? (HINT: TO CALCULATE THE NUMBER OF DAYS, DIVIDE THE NUMBER OF MONTHS BY 12 AND MULTIPLY BY 365)

deposit = 20000
r = .11
n_months = 9
n_days = (n_months / 12) * 365
deposit * (1 + r / 365)^n_days

#CORRECT
```

```{r}
# FINDING FUTURE VALUE
fv = 0
pv = 3750
r = .15
n = 2
t = 14

fv = pv * (1 + r / n) ^ (n * t); fv
```

```{r}
# YOU BOUGHT AN ANNUITY SELLING AT $8513.21 TODAY THAT PROMISES TO MAKE EQUAL PAYMENTS AT THE BEGINNING OF EACH YEAR FOR THE NEXT 10 YEARS (N). IF THE ANNUITY'S APPROPRIATE INTEREST RATE (I) REMAINS AT 5.00% DURING THIS TIME, THEN THE VALUE OF THE ANNUAL ANNUITY PAYMENT (PMT) IS __.

# =PMT(5%,10,-8513.21,,1)
#1050.00
#CORRECT ANSWER ^
```

```{r}
# YOU JUST WON THE LOTTERY. CONGRATUATIONS! THE JACKPOT IS $85,000,000, PAID IN 10 EQUAL ANNUAL PAYMENTS. THE FIRST PAYMENT ON THE LOTTERRY JACKPOT WILL BE MADE TODAY. IN PRESENT VALUE TERMS, YOU REALLY WON ___ - ASSUMING AN ANNUAL INTEREST RATE OF 5.00%.

winnings = 85000000
n_equal_payments = 10
r = .05
avg = winnings / n_equal_payments

amount = avg * (( 1 - (1 / (1 + r) ^ n_equal_payments)) / r) * (1 + r); amount

#correct
```


```{r}
# YOUR GRANDFATHER WANTS TO ESTABLISH A SCHOLARSHIP IN HIS FATHER’S NAME AT A LOCAL UNIVERSITY AND HAD STIPULATED THAT YOU WILL ADMINISTER IT. AS YOU’VE COMMITTED TO FUND A $5000 SCHOLARSHIP EVER YEAR BEGINNING ONE YEAR FROM TOMORROW, YOU’LL WANT TO SET ASIDE THE MONEY FOR THE SCHOLARSHIP IMMEDIATELY. AT TOMORROW’S MEETING WITH YOU GRANDFATHER AND THE BANK’S REPRESENTATIVE, YOU WILL NEED TO DEPOSIT __________ SO THAT YOU CAN FUND THE SCHOLARSHIP FOREVER, ASSUMING THAT THE ACCOUNT WILL EARN 4.50% PER ANNUM EVERY YEAR.

5000 / 0.045
25000 / .0425
25000 * 20
500000
500001
```

```{r}
# Find the future values of these ordinary annuities. Compounding occurs once a year. Do not round intermediate calculations. Round your answers to the nearest cent.

#annuity due is 12-1
#ordinary is 11-0
pmt = 200
r = .06
t = 12

pmt * (1 + r)^10 + pmt * (1 + r)^9 + pmt * (1 + r)^8 + pmt * (1 + r)^7 + pmt * (1 + r)^6 + pmt * (1 + r)^5 + pmt * (1 + r)^4 + pmt * (1 + r)^3 + pmt * (1 + r)^2 + pmt * (1 + r)^1 + pmt * (1 + r)^0

pmt * (1 + r)^12 + pmt * (1 + r)^11 + pmt * (1 + r)^10 + pmt * (1 + r)^9 + pmt * (1 + r)^8 + pmt * (1 + r)^7 + pmt * (1 + r)^6 + pmt * (1 + r)^5 + pmt * (1 + r)^4 + pmt * (1 + r)^3 + pmt * (1 + r)^2 + pmt * (1 + r)^1 + pmt * (1 + r)^0

pmt * (1 + r)^12 + pmt * (1 + r)^11 + pmt * (1 + r)^10 + pmt * (1 + r)^9 + pmt * (1 + r)^8 + pmt * (1 + r)^7 + pmt * (1 + r)^6 + pmt * (1 + r)^5 + pmt * (1 + r)^4 + pmt * (1 + r)^3 + pmt * (1 + r)^2 + pmt * (1 + r)^1 + pmt * (1 + r)^0
```


```{r}
#Suppose a U.S. treasury bond will pay $2,500 five years from now. If the going interest rate on 5-year treasury bonds is 4.25%, how much is the bond worth today?

pmt = 2500
years = 5
r = .0425

pmt / (1 + r)^years
```

```{r}
# You want to quit your job and return to school for an MBA degree 3 years from now, and you plan to save $7,000 per year, beginning immediately. You will make 3 deposits in an account that pays 5.2% interest. Under these assumptions, how much will you have 3 years from today

save = 7000
years = 3
r = 0.052

save * (1 + r) ^ 3 + save * (1 + r) ^ 2 + save * (1 + r) ^ 1
```

```{r}
#Last year Dania Corporation's sales were $525 million. If sales grow at 7.5% per year, how large (in millions) will they be 8 years later?

sales = 525
r = .075
years = 8

sales * (1 + r) ^ years
```


```{r}
# You deposit $1,000 today in a savings account that pays 3.5% interest, compounded annually. How much will your account be worth at the end of 25 years?

dep = 1000
r = .035
t = 25
n = 1

dep * (1 + r/n)^(n*t)
```


```{r}
# Last year Thomson Inc's earnings per share were $3.50, and its growth rate during the prior 5 years was 9.0% per year. If that growth rate were maintained, how many years would it take for Thomson's EPS to triple?

a = 3
r = .09

log(a) / log(1 + r)
```

```{r}
# Ten years ago, Lucas Inc. earned $0.50 per share. Its earnings this year were $2.20. What was the growth rate in earnings per share (EPS) over the 10-year period?

years = 10
pershare = .50
earnings = 2.20

((earnings/pershare)^(1/years) - 1)* 100
```

```{r}
# You just inherited some money, and a broker offers to sell you an annuity that pays $5,000 at the end of each year for 20 years. You could earn 5% on your money in other investments with equal risk. What is the most you should pay for the annuity?

pays = 5000
years = 20
r = .05

#= PV(5%,20,-5000,0)
```

```{r}
# Suppose an Exxon Corporation bond will pay $4,500 ten years from now. If the going interest rate on safe 10-year bonds is 4.25%, how much is the bond worth today?

pay = 4500
years = 10
r = .0425
pay / (1 + r)^years
```

```{r}
# Riverside Bank offers to lend you $50,000 at a nominal rate of 6.5%, compounded monthly. The loan (principal plus interest) must be repaid at the end of the year. Midwest Bank also offers to lend you the $50,000, but it will charge an annual rate of 7.0%, with no interest due until the end of the year. How much higher or lower is the effective annual rate charged by Midwest versus the rate charged by Riverside?

#.30%
```

```{r}
# What annual payment must you receive in order to earn a 6.5% rate of return on a perpetuity that has a cost of $1,250?

cost = 1250
r = .065

cost * r
```

```{r}
#Suppose your credit card issuer states that it charges a 15.00% nominal annual rate, but you must make monthly payments, which amounts to monthly compounding. What is the effective annual rate?

nom = .15
monthly = 12
(((1 + nom/monthly)^monthly) - 1 )* 100
```

```{r}
# Your uncle has $375,000 and wants to retire. He expects to live for another 25 years, and he also expects to earn 7.5% on his invested funds. How much could he withdraw at the beginning of each of the next 25 years and end up with zero in the account?

# $31 294.42 since your uncle will be receiving the payments at the BEGINNING of the year. The answer of $33 641.50 is what your uncle would get if he received the funds at the END of the year.
```

```{r}
# Suppose a bank offers to lend you $10,000 for 1 year on a loan contract that calls for you to make interest payments of $250.00 at the end of each quarter and then pay off the principal amount at the end of the year. What is the effective annual rate on the loan?

nom = 250/10000

quarterly = 4


(((1 + nom*quarterly/quarterly)^quarterly) -1)*100
```

```{r}
# Suppose you borrowed $14,000 at a rate of 10.0% and must repay it in 5 equal installments at the end of each of the next 5 years. How much interest would you have to pay in the first year?

borrow = 14000
r = .10
# equal installment=$14,000/PVAF for 5 years @10%=$14,000/3.7908=$3,693

so Interest portion=$14,000*10%=$1,400 Principle portion=$3,693-$1,400=2,293
```

