---
title: "Kevin Wong"
output:
  html_document:
    toc: yes
    theme: readable
---

***

# Introduction

<center>Hello, I am Kevin Wong!</center>

<center>This website was created by me. I am a Statistics student at the University of Illinois at Urbana-Champaign. I *LOVE* my school! [Go Illini!](https://fightingillini.com){target="_blank"}</center>  

<br>

<center>On this website, you can find out more information about me. I enjoy mathematics and computer science. My dream job is to be a computer engineer one day.</center>

<br>

<center>I will be graduating from the University of Illinois in Spring $2019$. My college GPA is currently $3.85$.</center>

***

# Work Experience (to be continued)

### Irwin Academic Center

Content Tutor - University of Illinois Division of Intercollegiate Athletics - Irwin Academic Services

### Kane County Cougars

Accounting Intern for Kane County Cougars (Class-A Affilate of MLB Arizona Diamondbacks)

***

# Projects (to be continued)

### Analyzing Illinois Basketball Data
### Analyzing NFL Rushing Yards Data
### Ross MacNeill Foundation Skate-A-Thon

***

# Schoolwork

[Kevin's Schoolwork](schoolwork.html)

***

# Contact Information

Email: <kjwong2@illinois.edu> 

LinkedIn: [linkedin.com/in/kevinjameswong](https://www.linkedin.com/in/kevinjameswong/){target="_blank"} 

GitHub: [github.com/kevinjameswong](https://github.com/kevinjameswong){target="_blank"}

Here is my resume! [Resume](Kevin Wong Resume)  

I am still working on this website, so there is still a lot that needs to be improved. For example, that resume link doesn't work. Last updated: May $23$, $2018$ at $11$:$51$ PM.

***
