---
title: "Kevin Wong - Running Data"
output:
  html_document:
    toc: yes
---

```{r cars, echo = FALSE, warning = FALSE, message = FALSE}
library(lubridate)
library(knitr)
library(kableExtra)
library(tidyverse)
library(stringr)
library(dplyr)
library(ggplot2)
#summary(cars)

#View(cars)

#str(cars)



# is how you comment
# command + shift + enter = run entire chunk
# shift + enter = run one line of chunk
```


```{r eval = FALSE}
str()
View()
```

# Test
## Including Plots
<!--
this is how you can create tabs for table of contents
-->

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



```{r}
test = function(distance, minutes) {
  m = 2
  s = 2 * distance + minutes
  return(s)
}

test(distance = 2, minutes = 5)
```




```{r}
test2 = function(distance, minutes) {
  m = 2
  s = 2 * distance + minutes
  return(s)
}


test2 = function(distance, minutes) {
  m = 2
  s = 2 * distance + minutes
  return(s)
}

test3 = function(x){
  k = sample(x, 1)
  return(k)
}

test3(x = 9)
```





