---
title: "Kevin Wong - Korean"
output:
  html_document:
    toc: no
---

```{r echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(gghighlight)
library(ggplot2)
library(kableExtra)
library(knitr)
library(lubridate)
library(rlang)
library(shiny)
library(shinydashboard)
library(stringr)
library(tidyverse)
```

```{r echo = FALSE}
Update_Date = as.Date("2-1-2025", format = "%m-%d-%Y")
Today_Date = Sys.Date()
```


<style type="text/css">
body .main-container {
	max-width: 1080px !important;
}
</style>


<h1>Languages</h1>

<p class="last-updated">
Last updated: `r paste(format(x = Update_Date, format = "%B"), " ", format(x = Update_Date, format = "%d") %>% as.numeric(), ", ", format(x = Update_Date, format = "%Y") %>% as.numeric(), sep = "")`
</p>

***

<p class="korean">
안녕하세요! 저는 케빈입니다. 감사합니다.
</p>

***

<p class="last-updated">
Please use my Shiny app to practice Korean and test your knowledge.
</p>

<div class="shiny-container">
<iframe src="https://kevinjameswong.shinyapps.io/korean/">
</iframe>
</div>



```{r echo = FALSE, eval = FALSE}
Silent ㅌ = 4
Silent ㅅ = 4
Silent ㅈ = 4
Silent ㅂ = 4



Silent ㄹ = 3

if ㄹ = 3,  ㅂ = 4, the ㅂ is silent. yal
if ㅂ = 3,  ㅅ = 4, the ㅅ is silent. eop
if ㄹ = 3,  ㅅ = 4, the ㅅ is silent. gol

얹 = eon
꽃 = kkot
갖 = gat
꽃히 = kkochi
그렇지 = geureochi
노랗다 = norata
핥 = hal
몫 = mok
놆 = nop
앉 = an
흙 = heuk
덟 = deol
얇 = yal
앞 = ap
앞문 = ammun
흙으로 = heulgeuro
덟 = deol
짧 = jjal
읽 = ik
옮 = om
찮다 = chanta
여덟= yeodeol
옮다 = omda
면 = anjeumyeon
점젆다 = ?
얹지 = eonji
옰에 = olse
얇아 = yalba
젊 = jeom
없지 = eopji
없으면 = eopseumyeon
닮았다 = dalmatda
않고 = anko
앉고 = ango
읽지 = ikji
옳다 = olta
싫= sil 
없 = eop
많지 = manchi
읽다 = ikda
싫고 = silko
핥다 = halda
짧다 = jjalda
```





