---
title: "Kevin Wong - Romanization Practice"
output:
  html_document:
    toc: no
---

```{r echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(ggplot2)
library(kableExtra)
library(knitr)
library(lubridate)
library(rlang)
library(shiny)
library(shinydashboard)
library(stringr)
library(tidyverse)
```

```{r echo = FALSE}
Update_Date = as.Date("02-28-2025", format = "%m-%d-%Y")
Today_Date = Sys.Date()
```

<style type="text/css">

.r33m_vid {
   font-family: Tahoma;
   color: black;
}

body, p {
   font-family: "Times New Roman";
   font-size: 18px;
}

</style>


<h1>Awards & Certificates</h1>

<p class="last-updated">
Last updated: `r paste(format(x = Update_Date, format = "%B"), " ", format(x = Update_Date, format = "%d") %>% as.numeric(), ", ", format(x = Update_Date, format = "%Y") %>% as.numeric(), sep = "")`
</p>

***




```{r echo = FALSE, message = FALSE, warning = FALSE}
korean_duo = read.csv(file = "files/duolingo_korean.csv") %>%
  select(Korean, Confirmed.Duolingo.Romanization) %>%
  unique() %>%
  filter(Korean != "")
korean_duo$Index = korean_duo %>% nrow() %>% seq.int()
names(korean_duo) = c("Korean", "Romanization", "Index")
```


```{r}
mydata = data.frame(
  TT = 5
)

mydata

mydata = rbind(mydata, TT = 1)
mydata
?reactiveValues
```





