---
title: "Kevin Wong - Kevin's Schoolwork"
output:
  html_document:
    toc: yes
---

<style type="text/css">

.swag {
   font-family: Tahoma;
   color: black;
}

</style>

***

<h1>Kevin's Schoolwork</h1>

I am a *Statistics* major at the **University of Illinois**. I am also minoring in *Leadership Studies* and *Business*. My GPA is $3.89$.

# Courses Taken

***

## Statistics

Some of the Statistics Courses I have taken include:  

- **STAT $385$**: Statistics Programming Methods            (Grade: A+)
- **STAT $400$**: Statistics and Probability I              (Grade: A)
- **STAT $410$**: Statistics and Probability II             (Grade: A-)
- **STAT $420$**: Methods of Applied Statistics             (Grade: A)
- **STAT $425$**: Applied Regression and Design             (Grade: A)
- **STAT $432$**: Basics of Statistical Learning            (Grade: A)
- **STAT $440$**: Statistical Data Management               (Grade: A)
- **STAT $448$**: Advanced Data Analysis                    (Grade: A)

My GPA in STAT courses at U of I is $3.96$.

## Leadership Studies

Some of the Leadership Studies Courses I have taken include:  

- **AGED $230$**: Leadership Communications            (Grade: A)
- **AGED $260$**: Introduction to Leadership Studies   (Grade: A+)
- **AGED $380$**: Leadership in Groups and Teams       (Grade: A+)
- **AGED $480$**: Collaborative Leadership             (Grade: A)

My GPA in Leadership courses at U of I is $4.00$.

## Business

Some of the Business Courses I have taken include:  

- **BADM $310$**: Management and Organizational Behavior  (Grade: A)
- **BADM $320$**: Principles of Marketing                 (Grade: TBD)
- **BADM $340$**: Ethical Dilemmas of Business            (Grade: A+)
- **ACCY $200$**: Fundamentals of Accounting              (Grade: A)
- **FIN $221$**: Corporate Finance                        (Grade: A)

My GPA in Business Courses at U of I is $4.00$.

***

# School Projects

<h3 class="swag">R33M Video</h3>

<iframe width="560" height="315" src="https://www.youtube.com/embed/SG5-_hInODw" frameborder="0" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>






```{r echo = FALSE, eval = FALSE}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120232594-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120232594-1');
</script>
```

