---
title: "Kevin Wong - Sleeping Data"
output:
  html_document:
    toc: yes
---

```{r echo = FALSE, warning = FALSE, message = FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
library(stringr)
Start_Date = as.Date("2/7/2017", format = "%m/%d/%Y")

percent = function(x, digits = 2, format = "f", ...) {
  formatC(100 * x, format = format, digits = digits, ...) %>% paste("%", sep = "")
}
```

```{r echo = FALSE}
Update_Date = as.Date("3/20/2019", format = "%m/%d/%Y")
```

```{r echo = FALSE}
sleep = read.csv("sleepdata.csv", sep = ";")
sleep$Sleep.quality = str_extract(string = sleep$Sleep.quality, pattern = "[0-9]{1,3}") %>% as.integer()
sleep$Time.in.bed = paste(str_extract(string = sleep$Time.in.bed, pattern = "[0-9]{1,2}") %>% as.integer(),
                          ifelse(
                            test = str_extract(string = sleep$Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.integer() <= 9,
                            yes = paste("0", str_extract(string = sleep$Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.integer(), sep = ""),
                            no = paste(str_extract(string = sleep$Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.integer(), sep = ""))
                          , sep = ":")
sleep$sleepmin = str_extract(string = sleep$Time.in.bed, pattern = "[0-9]{1,2}") %>% as.integer() * 60 + str_extract(string = sleep$Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.integer()

sleep$enddates = str_extract(string = sleep$End, pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}") %>% as.Date()

add_on = cbind(matrix(setdiff(c(as.Date(1:(Update_Date - Start_Date), origin = Start_Date)), str_extract(string = sleep$End, pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}") %>% as.Date()),
                      nrow = length(setdiff(c(as.Date(1:(Update_Date - Start_Date), origin = Start_Date)), str_extract(string = sleep$End, pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}") %>% as.Date())),
                      ncol = 1),
              matrix(NA,
                     nrow = length(setdiff(c(as.Date(1:(Update_Date - Start_Date), origin = Start_Date)), str_extract(string = sleep$End, pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}") %>% as.Date())),
                     ncol = ncol(sleep) - 1)) %>% as.data.frame()
add_on$V1 = as.Date(add_on$V1, origin = "1970-01-01")
names(add_on) = names(sleep)
add_on$enddates = add_on$Start
add_on$Start = add_on$End

sleep = rbind(sleep, add_on)

sleep = sleep[order(sleep$enddates, decreasing = FALSE), ]

sleep$Weekday = factor(x = rep(c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"), len = nrow(sleep)),
                       levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
```

<h1>Kevin's Sleeping Data</h1>

Last updated: March 20, 2019

***

<style type="text/css">

td, tr {
   font-family: "Times New Roman";
   font-size: 20px;
}

body, p {
   font-family: "Times New Roman";
   font-size: 18px;
}

</style>

I have been tracking my sleeping stats since February 6, 2017 using the [Sleep Cycle](https://www.sleepcycle.com){target="_blank"} app. It's a phenomenal app. Over the past `r nrow(sleep)` days, here are statistics on my past `r nrow(sleep) - (is.na(sleep$Sleep.quality) %>% sum())` sleeps.

***

```{r echo = FALSE}
groupby_weekday = sleep %>%
  group_by(Weekday) %>%
  summarise(total = Sleep.quality %>% ">="(0) %>% sum(na.rm = TRUE),
            avg_quality = Sleep.quality %>% mean(na.rm = TRUE) %>% "*"(100) %>% floor() %>% "/"(100),
            time_in_bed = paste(str_extract(string = Time.in.bed, pattern = "[0-9]{1,2}") %>% as.numeric() %>% "*"(60) %>% "+"(str_extract(string = Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.numeric()) %>% mean(na.rm = TRUE) %/% 60,
                                ifelse(str_extract(string = Time.in.bed, pattern = "[0-9]{1,2}") %>% as.numeric() %>% "*"(60) %>% "+"(str_extract(string = Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.numeric()) %>% mean(na.rm = TRUE) %>% floor() <= 9,
                                       yes = paste("0", str_extract(string = Time.in.bed, pattern = "[0-9]{1,2}") %>% as.numeric() %>% "*"(60) %>% "+"(str_extract(string = Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.numeric()) %>% mean(na.rm = TRUE) %>% floor() %% 60, sep = ""),
                                       no = paste(str_extract(string = Time.in.bed, pattern = "[0-9]{1,2}") %>% as.numeric() %>% "*"(60) %>% "+"(str_extract(string = Time.in.bed, pattern = ":[0-9]{1,2}") %>% str_extract(pattern = "[0-9]{1,2}") %>% as.numeric()) %>% mean(na.rm = TRUE) %>% floor() %% 60)), sep = ":")
            #nap_prob = paste((Sleep.Notes %>% str_detect(pattern = "Took a nap \\(1 hour\\)") %>% sum(na.rm = TRUE) + Sleep.Notes %>% str_detect(pattern = "Took a nap \\(1.5 hours\\)") %>% sum(na.rm = TRUE) + Sleep.Notes %>% str_detect(pattern = "Took a nap \\(2 hours\\)") %>% sum(na.rm = TRUE)) %>% "/"(Sleep.quality %>% ">="(0) %>% sum(na.rm = TRUE)) %>% "*"(10000) %>% floor() %>% "/"(100), "%", sep = ""),
            #avg_footsteps = Activity..steps. %>% mean(na.rm = TRUE) %>% floor()
            )

names(groupby_weekday) = c("Weekday", "Sleeps Recorded", "Sleep Quality (%)", "Average Time in Bed")#, "Average Footsteps")

kable(groupby_weekday, format = "html", align = "lrrrr") %>%
  kable_styling(bootstrap_options = c("hover", "responsive"))
```

```{r echo = FALSE, eval = FALSE}
groupby_weekday = sleep %>%
  group_by(Weekday) %>%
  summarise(S = Sleep.Notes %>% str_extract(pattern = "Took a nap") %>% sum()
            )

names(groupby_weekday) = c("Weekday", "Sleeps Recorded", "Sleep Quality (%)", "Average Time in Bed", "Average Footsteps")

kable(groupby_weekday, format = "html", align = "lrrr") %>%
  kable_styling(bootstrap_options = c("hover", "responsive"))
```


