---
title: "Kevin Wong - Music Data"
output:
  html_document:
    toc: yes
---

```{r echo = FALSE, message = FALSE, warning = FALSE}
Update_Date = as.Date("01-01-2025", format = "%m-%d-%Y")
#Update_Date

library(tidyverse)
library(dplyr)
library(lubridate)
library(knitr)
library(kableExtra)
library(tidyverse)
library(stringr)
library(ggplot2)
library(shiny)
```

<h1>Spotify Wrapped Data</h1>

<p class="last-updated">
Last updated: `r paste(format(x = Update_Date, format = "%B"), " ", format(x = Update_Date, format = "%d") %>% as.numeric(), ", ", format(x = Update_Date, format = "%Y") %>% as.numeric(), sep = "")`
</p>

<hr />


```{r echo = FALSE, message = FALSE, warning = FALSE}
spotify = read.csv("~/Documents/KevinWebsite/kevinjameswong.github.io/files/SpotifyWrapped.csv")

spotify =
  spotify %>%
  select(Year,
         Ranking,
         Song,
         Album,
         Artist.1,
         Artist.2,
         Artist.3,
         Artist.4,
         Artist.5,
         Artist.6,
         Approx.Genre)

spotify = spotify %>%
  group_by(Year) %>%
  mutate(
    Score = max(row_number()) + 1 - row_number(),
    Count = 1,
    RecordInt = row_number()
  ) %>%
  filter(Song != "")

names(spotify) = c("Year", "Ranking", "Song", "Album", "Artist", "Artist2", "Artist3", "Artist4", "Artist5", "Artist6", "Genre", "Score", "Count", "RecordInt")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
#https://mastering-shiny.org/basic-ui.html

#selectInput = dropdown
#sliderInput = slider
#textInput
#passwordInput
#textAreaInput
#numericInput("num", "Number one", value = 0, min = 0, max = 100),
#dateInput("dob", "When were you born?"),
#dateRangeInput

uix = fluidPage(
  selectInput(inputId = "dataset", label = "Dataset", choices = spotify$Artist %>% unique() %>% sort(), selected = "TWICE"),
  textOutput("textdelulu"),
  verbatimTextOutput("summary"),
  tableOutput("table"),
  mainPanel(
      textOutput("DataTable")
  )
)

serverx = function(input, output, session) {
  output$textdelulu = renderText({paste("Ok")})
  output$summary = renderPrint({
    dataset = get(input$dataset, spotify)
    max(dataset)
  })
  output$table = renderText({
    spotify %>%
      select(Year, Ranking, Song, Artist, Genre, Score) %>%
      filter(Artist == input$dataset) %>%
      kable(format = "html", align = "l") %>%
      kable_styling(bootstrap_options = c("hover", "responsive")) %>%
      scroll_box(width = "100%", height = "100%")
  })
}

shinyApp(ui = uix, server = serverx)
```

```{r echo = FALSE, eval = FALSE, message = FALSE, warning = FALSE}
ui = fluidPage(
  selectInput("dataset", label = "Dataset", choices = (spotify$Artist1)),
  verbatimTextOutput("summary"),
  tableOutput("table")
)
server = function(input, output, session) {
  # Create a reactive expression
  dataset <- reactive({
    get(input$dataset, spotify)
  })

  output$summary <- renderPrint({
    # Use a reactive expression by calling it like a function
    summary(dataset())
  })
  
  output$table <- renderTable({
    dataset()
  })
}
shinyApp(ui, server)


AllArtists_AllYears = spotify %>%
  group_by(Artist1)   %>%
  summarize(xt = sum(Score),
            xt2 = n()) %>%
  rename("Score" = xt, "Artist" = Artist1, "TT" = xt2) %>%
  arrange(desc(Score))




```

```{r echo = FALSE, eval = FALSE}
ui = fluidPage(
  selectInput("dataset", label = "Dataset", choices = ls(spotify)),
  verbatimTextOutput("summary"),
  tableOutput("table")
)

server = function(input, output, session) {
  # Create a reactive expression
  dataset = reactive({
    get(input$dataset, spotify)
  })

  output$summary <- renderPrint({
    # Use a reactive expression by calling it like a function
    summary(dataset())
  })
  
  output$table <- renderTable({
    dataset()
  })
}
shinyApp(ui, server)

```









```{r}
ui <- fluidPage(

  # App title ----
  titlePanel("Sliders"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar to demonstrate various slider options ----
    sidebarPanel(

      # Input: Simple integer interval ----
      sliderInput("integer", "Integer:",
                  min = 0, max = 1000,
                  value = 500),

      # Input: Decimal interval with step value ----
      sliderInput("decimal", "Decimal:",
                  min = 0, max = 1,
                  value = 0.5, step = 0.1),

      # Input: Specification of range within an interval ----
      sliderInput("range", "Range:",
                  min = 1, max = 1000,
                  value = c(200,500)),

      # Input: Custom currency format for with basic animation ----
      sliderInput("format", "Custom Format:",
                  min = 0, max = 10000,
                  value = 0, step = 2500,
                  pre = "$", sep = ",",
                  animate = TRUE),

      # Input: Animation with custom interval (in ms) ----
      # to control speed, plus looping
      sliderInput("animation", "Looping Animation:",
                  min = 1, max = 2000,
                  value = 1, step = 10,
                  animate =
                    animationOptions(interval = 300, loop = TRUE))

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Table summarizing the values entered ----
      tableOutput("values")

    )
  )
)

server <- function(input, output) {

  # Reactive expression to create data frame of all input values ----
  sliderValues <- reactive({

    data.frame(
      Name = c("Integer",
               "Decimal",
               "Range",
               "Custom Format",
               "Animation"),
      Value = as.character(c(input$integer,
                             input$decimal,
                             paste(input$range, collapse = " "),
                             input$format,
                             input$animation)),
      stringsAsFactors = FALSE)

  })

  # Show the values in an HTML table ----
  output$values <- renderTable({
    sliderValues()
  })

}

shinyApp(ui, server)
```





```{r}
ui <- fluidPage(
  sliderInput("x", "If x is", min = 1, max = 50, value = 30),
  sliderInput("y", "and y is", min = 1, max = 50, value = 5),
  "then, (x * y) is", textOutput("product"),
  "and, (x * y) + 5 is", textOutput("product_plus5"),
  "and (x * y) + 10 is", textOutput("product_plus10")
)

server <- function(input, output, session) {
  output$product <- renderText({ 
    product <- input$x * input$y
    product
  })
  output$product_plus5 <- renderText({ 
    product <- input$x * input$y
    product + 5
  })
  output$product_plus10 <- renderText({ 
    product <- input$x * input$y
    product + 10
  })
}

shinyApp(ui, server)
```

```{r echo = FALSE, eval = FALSE}
spotify %>% group_by(Song) %>% summarise(
  score = sum(Score)
)
```

```{r echo = FALSE, echo = FALSE, eval = FALSE}
spotify %>%
  group_by(Album)   %>%
  count(Album)      %>%
  rename(Count = n) %>%
  arrange(desc(Count))

names(groupby_yearmonth) = c("Month", "Total Runs", "Total Run Days", "Days Off", "Miles", "Time", "Pace", "Miles Per Run", "Miles Per Day", "Yearly Mile Rate", "MPH", "Total Calories Burned")

kable(x = groupby_yearmonth, format = "html", align = "lrrrrrrrrrrrrrr") %>%
  kable_styling(bootstrap_options = c("hover", "responsive")) %>%
  scroll_box(width = "100%", height = "100%")
```

```{r Most Popular Songs, echo = FALSE, eval = FALSE}
spotify %>%
  group_by(Song, Artist.1, Artist.2, Artist.3, Artist.4, Artist.5, Artist.6) %>%
  count(Song, Artist.1, Artist.2, Artist.3, Artist.4, Artist.5, Artist.6, Total = sum(Score)) %>%
  rename(Appearances = n) %>%
  arrange(desc(Total), desc(Appearances))
```

```{r Most Popular Artists, warning = FALSE, echo = FALSE, eval = FALSE}
a1 = spotify %>%
  count(Artist.1) %>%
  rename(Total = n, Artist = Artist.1)
a2 = spotify %>%
  count(Artist.2) %>%
  rename(Total = n, Artist = Artist.2)
a3 = spotify %>%
  count(Artist.3) %>%
  rename(Total = n, Artist = Artist.3)
a4 = spotify %>%
  count(Artist.4) %>%
  rename(Total = n, Artist = Artist.4)
a5 = spotify %>%
  count(Artist.5) %>%
  rename(Total = n, Artist = Artist.5)
a6 = spotify %>%
  count(Artist.6) %>%
  rename(Total = n, Artist = Artist.6)

bind_rows(a1, a2, a3, a4, a5, a6) %>%
  arrange(Artist) %>%
  group_by(Artist) %>%
  summarize(Total = sum(Total)) %>%
  arrange(desc(Total)) %>%
  tail(n = -1)
```


```{r Songs on 2016 and 2017, echo = FALSE, eval = FALSE}
spotify %>%
  filter(Year == 2016 | Year == 2017) %>%
  arrange(Song) %>%
  group_by(Song, Artist.1) %>%
  count(Song, Total = sum(Score)) %>%
  rename(Appearances = n) %>%
  filter(Appearances == 2) %>%
  arrange(desc(Total))
```

```{r Songs on 2017 and 2018, echo = FALSE, eval = FALSE}
spotify %>%
  filter(Year == 2017 | Year == 2018) %>%
  arrange(Song) %>%
  group_by(Song, Artist.1) %>%
  count(Song, Total = sum(Score)) %>%
  rename(Appearances = n) %>%
  filter(Appearances == 2) %>%
  arrange(desc(Total))
```

```{r Songs on 2016 and 2018, echo = FALSE, eval = FALSE}
spotify %>%
  filter(Year == 2016 | Year == 2018) %>%
  arrange(Song) %>%
  group_by(Song, Artist.1) %>%
  count(Song, Total = sum(Score)) %>%
  rename(Appearances = n) %>%
  filter(Appearances == 2) %>%
  arrange(desc(Total))
```








