---
title: "Kevin Wong - Music Data"
output:
  html_document:
    toc: yes
---

```{r echo = FALSE, message = FALSE, warning = FALSE}
Update_Date = as.Date("01-01-2025", format = "%m-%d-%Y")
#Update_Date

library(dplyr)
library(ggplot2)
library(kableExtra)
library(knitr)
library(lubridate)
library(rlang)
library(shiny)
library(stringr)
library(tidyverse)
```

<h1>Spotify Wrapped Data</h1>

<p class="last-updated">
Last updated: `r paste(format(x = Update_Date, format = "%B"), " ", format(x = Update_Date, format = "%d") %>% as.numeric(), ", ", format(x = Update_Date, format = "%Y") %>% as.numeric(), sep = "")`
</p>

<hr />

```{r echo = FALSE, message = FALSE, warning = FALSE}
spotify = read.csv("~/Documents/KevinWebsite/kevinjameswong.github.io/files/SpotifyWrapped.csv")

spotify =
  spotify %>%
  select(Year,
         Ranking,
         Song,
         Album,
         Artist.1,
         Artist.2,
         Artist.3,
         Artist.4,
         Artist.5,
         Artist.6,
         Approx.Genre)

spotify = spotify %>%
  group_by(Year) %>%
  mutate(
    Score = max(row_number()) + 1 - row_number(),
    Count = 1,
    RecordInt = row_number()
  ) %>%
  filter(Song != "")

names(spotify) = c("Year", "Song Ranking", "Song", "Album", "Artist", "Artist2", "Artist3", "Artist4", "Artist5", "Artist6", "Genre", "Score", "Count", "RecordInt")
```


<p class="last-updated">
I have been collecting my Spotify Wrapped data since `r min(spotify$Year)`. I have `r length(table(spotify$Year))` years worth of data, from `r min(spotify$Year)` - `r max(spotify$Year)`.
</p>

<iframe height="400" width="100%" frameborder="no" src="https://kevinjameswong.shinyapps.io/spotify/">
</iframe>


