---
title: "Kevin Wong - Music Data"
output:
  html_document:
    toc: yes
---

```{r echo = FALSE, message = FALSE, warning = FALSE}
Update_Date = as.Date("01-01-2025", format = "%m-%d-%Y")
#Update_Date

library(dplyr)
library(ggplot2)
library(kableExtra)
library(knitr)
library(lubridate)
library(rlang)
library(shiny)
library(stringr)
library(tidyverse)
```

<h1>Spotify Wrapped Data</h1>

<p class="last-updated">
Last updated: `r paste(format(x = Update_Date, format = "%B"), " ", format(x = Update_Date, format = "%d") %>% as.numeric(), ", ", format(x = Update_Date, format = "%Y") %>% as.numeric(), sep = "")`
</p>

<hr />

```{r echo = FALSE, message = FALSE, warning = FALSE}
spotify = read.csv("~/Documents/KevinWebsite/kevinjameswong.github.io/files/SpotifyWrapped.csv")

spotify =
  spotify %>%
  select(Year,
         Ranking,
         Song,
         Album,
         Artist.1,
         Artist.2,
         Artist.3,
         Artist.4,
         Artist.5,
         Artist.6,
         Approx.Genre)

spotify = spotify %>%
  group_by(Year) %>%
  mutate(
    Score = max(row_number()) + 1 - row_number(),
    Count = 1,
    RecordInt = row_number()
  ) %>%
  filter(Song != "")

names(spotify) = c("Year", "Song Ranking", "Song", "Album", "Artist", "Artist2", "Artist3", "Artist4", "Artist5", "Artist6", "Genre", "Score", "Count", "RecordInt")
```


```{r echo = FALSE, message = FALSE, warning = FALSE}
TopArtists_AllTime =
  spotify %>%
  group_by(Artist) %>%
  summarize(xt = sum(Score), Song_Count = n()) %>%
  rename("Score" = xt) %>%
  arrange(desc(Score)) %>%
  mutate(Rank = row_number(), xx = str_sub(string = row_number(), start = (row_number() %>% str_length()), end = 100) %>% as.integer())

TopArtists_AllTime = 
  TopArtists_AllTime %>%
  mutate(
    Rank_Text = ifelse(xx == 1, str_c(Rank %>% as.character(), "st"),
          ifelse(xx == 2, str_c(Rank %>% as.character(), "nd"),
          ifelse(xx == 3, str_c(Rank %>% as.character(), "rd"),
          str_c(Rank %>% as.character(), "th"))))
  ) %>%
      select(Artist, Score, Song_Count, Rank, Rank_Text)

ttt = c("Gone West", "TWICE", "Morgan Wallen", "Georgia Webster", "Red Rocks Worship", "Caitlyn Smith", "Lil Wayne", "Bethel Music", "OneRepublic", "Hillsong UNITED", "The Fray", "Lady A", "Jesus Culture", "Elevation Worship", "Keane", "Gavin DeGraw", "Hanson", "Ed Sheeran", "Train")
# ttt = spotify$Artist
```


```{r echo = FALSE, message = FALSE, warning = FALSE}
TopArtists_ByYear =
  spotify %>%
  group_by(Artist, Year) %>%
  summarize(xt = sum(Score), Song_Count = n()) %>%
  rename("Score" = xt) %>%
  arrange(Year, desc(Score), Artist) %>%
  group_by(Year) %>%
  mutate(Rank = row_number(Year), xx = str_sub(string = row_number(Year), start = (row_number(Year) %>% str_length()), end = 100) %>% as.integer())

TopArtists_ByYear = 
  TopArtists_ByYear %>%
  mutate(
    Rank_Text = ifelse(xx == 1, str_c(Rank %>% as.character(), "st"),
          ifelse(xx == 2, str_c(Rank %>% as.character(), "nd"),
          ifelse(xx == 3, str_c(Rank %>% as.character(), "rd"),
          str_c(Rank %>% as.character(), "th"))))
  ) %>%
      select(Artist, Year, Score, Song_Count, Rank, Rank_Text)

TopArtists_ByYear$Year = as.factor(TopArtists_ByYear$Year)
TopArtists_ByYear$Rank = as.integer(TopArtists_ByYear$Rank)

TopArtists_ByYear$Brave = max(TopArtists_ByYear$Rank) + 1
TopArtists_ByYear$NewRank = TopArtists_ByYear$Brave - TopArtists_ByYear$Rank
```

<p class="last-updated">
I have been collecting my Spotify Wrapped data since `r min(spotify$Year)`. I have `r length(table(spotify$Year))` years worth of data, from `r min(spotify$Year)` - `r max(spotify$Year)`.
</p>


```{r echo = FALSE, message = FALSE, warning = FALSE}
#https://mastering-shiny.org/basic-ui.html

#selectInput = dropdown
#sliderInput = slider
#textInput
#passwordInput
#textAreaInput
#numericInput("num", "Number one", value = 0, min = 0, max = 100),
#dateInput("dob", "When were you born?"),
#dateRangeInput

uix = fluidPage(
  titlePanel(title = "Favorite Artists"),
  selectInput(inputId = "SelectedArtist", label = "Select Artist:", choices = ttt %>% unique() %>% sort(), selected = "TWICE"),
  
  
  htmlOutput("Keeps"),

  tableOutput("table"),
  
  plotOutput("plot2"),
  
  textOutput(ttt),
  textOutput("Rank_Textx"),
  textOutput("textdelulu"),
  textOutput("textdelulu3"),
  verbatimTextOutput("summary"),
  
  mainPanel(
    textOutput("DataTable")
  )
)
  
serverx = function(input, output, session) {
  output$table = renderText({
    spotify %>%
      select(Year, `Song Ranking`, Song, Artist, Album) %>%
      filter(Artist == input$SelectedArtist) %>%
      kable(format = "html", align = "llll") %>%
      kable_styling(bootstrap_options = c("hover", "responsive")) %>%
      scroll_box(width = "100%", height = "100%")
  })
  
    output$Keeps = renderUI({
      
    t1 = TopArtists_AllTime[which(TopArtists_AllTime$Artist == input$SelectedArtist), 5] #try to make the 5 dynamic
    xxx1 = paste("According to Spotify Wrapped, ", input$SelectedArtist, " is my ", t1, " favorite artist overall. Here are my favorite songs from ", input$SelectedArtist, ", according to the data.", sep = "")
    
    t11 = TopArtists_AllTime %>% filter(TopArtists_AllTime$Artist == input$SelectedArtist) %>% select(Song_Count)
    xxx2 = paste(t11, " songs from ", input$SelectedArtist, " have appeared in my Spotify Wrapped all time.", sep = "")
    
    HTML(paste(xxx1, "</br>", "</br>", xxx2, "</br>", "</br>", sep = ""))
    })
    
    
    output$plot2 = renderPlot({

    ggplot(data = TopArtists_ByYear %>% filter(Artist == input$SelectedArtist), aes(x = Year, y = NewRank)) +
        geom_bar(stat = "identity", fill = "darkblue") +
        geom_text(aes(label = Rank_Text %>% format(nsmall = 2)), vjust = 1.6, color = "white", size = 5) +
        xlab(label = "Year") +
        ylab(label = "Rank") +
        ggtitle(label = "Artist Rank by Year") +
        theme(plot.title = element_text(hjust = 0.5))
    })

    
}
  
shinyApp(ui = uix, server = serverx)
```


















