---
title: "Untitled"
author: "Kevin Wong"
date: "8/15/2018"
output: html_document
---

```{r}
kayla$pff_PLAYID = as.factor(kayla$pff_PLAYERID)

length(which(kayla$pff_PLAYID == 1))
cumsum(c(TRUE, diff(kayla$pff_PLAYID) != 0))
kayla$pff_PLAYID = as.numeric(kayla$pff_PLAYERID)
which(length(cumsum(kayla$pff_PLAYID)) == 11)
```


```{r}
a = c(rep("A", each = 3), rep("B", each = 3), rep("C", each = 2))
b = c(1, 1, 2, 4, 1, 1, 2, 2)
df = data.frame(
  a = a,
  b = b
)

df = arrange(df, df$a)

df = df[unique(df$b), ]

df
aggregate(b ~ a, data = df, max)

df

AwareStaminaTotal %>%
  group_by(pff_PLAYERID) %>%
  summarize(numberplays = max(numberplays))

```


```{r}
s = c(4, 4, 5, 6, 6, 7, 7, 8, 8, 1, 1, 2, 3, 91, 91, 91, 92, 92, 93, 93, 93)
p = sort(s)
p
teams = c("CHI", "CHI", "ATL", "CHI", "ATL", "ATL", "CHI", "ATL", "ATL", "PIT", "PIT", "BUF", "BUF", "PIT", "PIT", "PIT", "BUF", "BUF", "PIT", "PIT", "PIT")
players = c(1, 2, 3, 2, 3, 4, 1, 2, 6, 7, 8, 9, 10, 7, 11, 12, 8, 9, 7, 13, 14)
 

fd = data.frame(
  p = p,
  players = players,
  teams = teams
)


df = arrange(fd, fd$teams, fd$p)

View(df)



df$l = cumsum(!duplicated(df$p))
t = cumsum(!duplicated(df$l))
table(t)
df$l
l = as.factor(df$p)
levels(l) = 1:length(unique(l))
df$l = l


as.factor(l)

as.list(transform(l), 1:11)

?with()

?sort()
as.numeric(as.character(l))
as.numeric(levels(l))[l]
```

```{r}
s = c(1, 2, NA)
sum(s, na.rm = TRUE)


cumsum(c(TRUE, diff(s) != 0))
```

```{r}
t = function(x) {
  rnorm(x, mean = 0, sd = 1)
}

set.seed(3)
sum(t(9))
```

